[[redirects]]
  from = "https://api.cartebrute.art"
  to = "http://157.230.110.237/graphql"
  status = 200
  force = true

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"